### ISSUE TITLE
pyterm

### ISSUE THREAD

**Issue by yeeters99** [MatrixTM/MultiAccountGenerator#11]
![Screenshot_9](https://user-images.githubusercontent.com/114696887/197016569-47b05ca0-4a64-4807-881d-2896d3b8090d.png)
Any idea how to fix this?

**Comment by BlackSnowDot** [comment]
check [this issues](https://github.com/BlackSnowDot/MultiAccountGenerator/issues/9#issuecomment-1280019795)
