### ISSUE TITLE
Output URL's

### ISSUE THREAD

**Issue by driv3n** [MatrixTM/MultiAccountGenerator#12]
I got the program to work, but its only printing URLS to an email address, how do we differenitate what service its for or if they work?

Did I mess up the source code or is this how it is intended to function?

**Comment by BlackSnowDot** [comment]
hello
you can check `conifg.json` file and any service you want
for example
```
    "bluealts": [
      "https://bluealts.net/",
      "https://bluealts.net/crunchyroll/",
      "https://bluealts.net/hulu/",
      "https://bluealts.net/nordvpn/",
      "https://bluealts.net/origin/",
      "https://bluealts.net/call-of-duty/",
      "https://bluealts.net/ipvanish/"
    ]
```

to 
```
    "bluealts": [
      "https://bluealts.net/",
      "https://bluealts.net/crunchyroll/",
      "https://bluealts.net/hulu/",
      "https://bluealts.net/ipvanish/"
    ]
```

or only 1 service

**Comment by driv3n** [comment]
I did this, thank you, as far as the output, is it supposed to be short URLs? 

Do you go and individually test them to see if the login works?

**Comment by BlackSnowDot** [comment]
yep, output is not email pass, because you need pass captcha
