### ISSUE TITLE
Help pls

### ISSUE THREAD

**Issue by FDALOIAPP** [MatrixTM/MultiAccountGenerator#13]
Hello, it is my first time using a generator and it is also my first time using python, I really like this generator and I would like to use it, but I have no idea of ​​how to open the program not even the least, do you have a tutorial on Youtube that can help? Thank you!

**Comment by BlackSnowDot** [comment]
I will record a video tomorrow❤️
also you can check [Document](https://github.com/BlackSnowDot/MultiAccountGenerator#-document)

**Comment by FDALOIAPP** [comment]
Thank you very much, what is your Youtube channel to follow you?

**Comment by BlackSnowDot** [comment]
i will make new account

**Comment by BlackSnowDot** [comment]
video added
