### ISSUE TITLE
No accounts

### ISSUE THREAD

**Issue by NeoZLender** [MatrixTM/MultiAccountGenerator#17]
Hey, I started generating accounts, but nothing appears in accounts.txt
I tried many times, but nothing  changes, help me please.

**Comment by BlackSnowDot** [comment]
fixed

**Comment by Ryko1321** [comment]
Bro that app generates a lot of links but I don`t know for what site they are.. how can I see?

**Comment by BlackSnowDot** [comment]
I fix it tomorrow

**Comment by xX-MoonWalker-Xx** [comment]
please close the issue if its solved

**Comment by zephr1213** [comment]
its a marketing ploy by bluealts. no accounts here.

**Comment by xX-MoonWalker-Xx** [comment]
> its a marketing ploy by bluealts. no accounts here.

This repository is not affiliated with bluealts in any way.
