### ISSUE TITLE
How to install and run?

### ISSUE THREAD

**Issue by Fortress937** [MatrixTM/MultiAccountGenerator#18]
i tried running pip3 install -r requirements.txt but nothing happened, it say pip is not recognized, even though i did install the python. Please help me.....

**Comment by BlackSnowDot** [comment]
install pip

**Comment by BlackSnowDot** [comment]
https://www.activestate.com/resources/quick-reads/how-to-install-and-use-pip3/
or
run this file https://bootstrap.pypa.io/get-pip.py

**Comment by Fortress937** [comment]
i tried, the first one i use the command that you provided, it keep saying pip3 is not recognized,

the second one, i run with .py, but it closes after opening without any effect.

**Comment by BlackSnowDot** [comment]
[this link](https://www.geeksforgeeks.org/how-to-install-pip-on-windows/#:~:text=Step%201%3A%20Download%20the%20get,where%20the%20above%20file%20exists.&text=Step%204%3A%20Now%20wait%20through%20the%20installation%20process.)
[or this link](https://www.youtube.com/watch?v=Ko9b_vC6XY0)
[maybe this](https://www.youtube.com/watch?v=qCG3NARH-bA)

---

![image](https://user-images.githubusercontent.com/95581741/204604948-bb4822b3-1124-4b27-81b0-b47e88023879.png)

**Comment by xX-MoonWalker-Xx** [comment]
> i tried running pip3 install -r requirements.txt but nothing happened, it say pip is not recognized, even though i did install the python. Please help me.....

did you click the `ADD PYTHON TO PATH` option when installing python?

**Comment by Fortress937** [comment]
> > i tried running pip3 install -r requirements.txt but nothing happened, it say pip is not recognized, even though i did install the python. Please help me.....
> 
> did you click the `ADD PYTHON TO PATH` option when installing python?

No

**Comment by xX-MoonWalker-Xx** [comment]
then uninstall python, then install again. but tick the `ADD TO PATH` option when installing

**Comment by Fortress937** [comment]
![image](https://user-images.githubusercontent.com/119410273/209666008-45afaaf1-55b3-48ba-9a53-fcff745c637b.png)


now i did install python with checked `ADD TO PATH`
but now........

**Comment by xX-MoonWalker-Xx** [comment]
try `py` instead

**Comment by Fortress937** [comment]
![image](https://user-images.githubusercontent.com/119410273/209681497-9fd641e8-cb83-42e6-96b9-44dfb6737723.png)

Nice, it works, thanks for your help
and one question.....how does these link works?

(Don't mind the Rickrolling face)

**Comment by xX-MoonWalker-Xx** [comment]
dude i even got rickrolled on github :|
open the links, solve the captcha, get the account

**Comment by BlackSnowDot** [comment]
done? can i close issues?

**Comment by Fortress937** [comment]
> dude i even got rickrolled on github :| open the links, solve the captcha, get the account

ooh i see....
anyway i will look on it thanks

**Comment by Fortress937** [comment]
> done? can i close issues?

thanks for your help, you can close this issues now if you wish.
