### ISSUE TITLE
This just gives you the link, you still need to goto the link and wait 15s right?

### ISSUE THREAD

**Issue by phillipbruh** [MatrixTM/MultiAccountGenerator#23]

**Comment by xX-MoonWalker-Xx** [comment]
yes as it has a captcha, we currently dont bypass it.

**Comment by bhargavjoshi1237** [comment]
and the id pass doesn't even works

**Comment by xX-MoonWalker-Xx** [comment]
> and the id pass doesn't even works

thats not a problem from the generator, as the accounts are scraped from a website. if the website is outdated, it wont work, you have to add another website for it.
