### ISSUE TITLE
Issue with generating

### ISSUE THREAD

**Issue by KeyeroDev** [MatrixTM/MultiAccountGenerator#25]
![image](https://user-images.githubusercontent.com/83180915/223501734-77e571a7-cba8-45fa-ad4f-b15ad559e6a1.png)
After running it stops after 4 tasks and doesnt send anything

**Comment by deadpoolstark** [comment]
Same issue

**Comment by dsous** [comment]
+1

**Comment by ghost** [comment]
same

**Comment by xX-MoonWalker-Xx** [comment]
@BlackSnowDot

**Comment by BlacKSnowDot0** [comment]
fixed
