### ISSUE TITLE
dosent even generate

### ISSUE THREAD

**Issue by MemeGang8** [MatrixTM/MultiAccountGenerator#27]
i mean it launches which is good but it shits itself when actually generating it's stuck at 4 Tasks created and nothing else happens
so im gonna say currently non working and may be outdated
![image](https://user-images.githubusercontent.com/78689819/232265535-0cce047d-bb43-4952-a536-72246bcef7d9.png)

**Comment by ArtMckenyu** [comment]
Netflix

**Comment by Zykxo** [comment]
> i mean it launches which is good but it shits itself when actually generating it's stuck at 4 Tasks created and nothing else happens so im gonna say currently non working and may be outdated ![image](https://user-images.githubusercontent.com/78689819/232265535-0cce047d-bb43-4952-a536-72246bcef7d9.png)

any luck? xd

**Comment by BlacKSnowDot0** [comment]
Hello, thanks for your report, i will update the generator as soon as possible

**Comment by Zykxo** [comment]
Hey, please let us know once its updated, thank you

**Comment by BlacKSnowDot0** [comment]
sure

**Comment by BlacKSnowDot0** [comment]
fixed
