### ISSUE TITLE
help please!!!

### ISSUE THREAD

**Issue by hmm-star** [MatrixTM/MultiAccountGenerator#38]

**Comment by BlacKSnowDot0** [comment]
There's a video in readme already

**Comment by hmm-star** [comment]
hi..i just tried everything and it is not working. all it says is error occured.

**Comment by BlacKSnowDot0** [comment]
What error exactly

**Comment by hmm-star** [comment]
nothing when i ran the main .py file i typed 0 and then it went on showing a list of links like short earn, curiosoty stream  with an error occured again and again. I would be thankful to you  is you can solve this problem
regards
--hmm-star

**Comment by BlacKSnowDot0** [comment]
can you please record a video of that, and send it here, thanks
