### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by TheKyogreGuy** [MatrixTM/MultiAccountGenerator#39]
Don't use the second you click on websites it gives viruses. My screen was covered in 2 seconds had to force factory reset hopefully it fixes.

**Comment by doggo890** [comment]
thanks

**Comment by DaveLovesTacos** [comment]
bro its open source no there isnt

**Comment by vedantakbari** [comment]
> bro its open source no there isnt

that doesnt always mean its real. My boy matrix is known though
