### ISSUE TITLE
Missing Module

### ISSUE THREAD

**Issue by AhanafMahmud** [MatrixTM/MultiAccountGenerator#9]
Hi u say to download pyterm but i cant find any module name pyterm

**Comment by xX-MoonWalker-Xx** [comment]
can you please provide the error code.

**Comment by AhanafMahmud** [comment]
Traceback (most recent call last):
  File "C:\Users\private\Downloads\Compressed\MultiAccountGenerator-main\MultiAccountGenerator-main\generator.py", line 9, in <module>
    from PyTerm import Console
ModuleNotFoundError: No module named 'PyTerm'

**Comment by xX-MoonWalker-Xx** [comment]
did you install the requirements first?
try: `python -m pip install -r requirements.txt`

**Comment by BlackSnowDot** [comment]
try this command
`pip install git+https://github.com/Its-Vichy/PyTerm.git`

**Comment by AhanafMahmud** [comment]
Kk I will both

**Comment by xX-MoonWalker-Xx** [comment]
please tell me the results of each command

**Comment by AhanafMahmud** [comment]
I still didn't try soo I will tell u if I do.Please wait

**Comment by AhanafMahmud** [comment]
python -m pip install -r requirements.txt=Collecting colorama~=0.4.5
  Using cached colorama-0.4.5-py2.py3-none-any.whl (16 kB)
ERROR: Could not find a version that satisfies the requirement PyTerm~=0.0.1 (from versions: none)
ERROR: No matching distribution found for PyTerm~=0.0.1

**Comment by AhanafMahmud** [comment]
btw i have python 3.10.8 downloaded into my system

**Comment by AhanafMahmud** [comment]
pip install git+https://github.com/Its-Vichy/PyTerm.git=Collecting git+https://github.com/Its-Vichy/PyTerm.git
  Cloning https://github.com/Its-Vichy/PyTerm.git to c:\users\ahana\appdata\local\temp\pip-req-build-mttxb6pg
  ERROR: Error [WinError 2] The system cannot find the file specified while executing command git version
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?

**Comment by AhanafMahmud** [comment]
these are the results i found while i process ur codes

**Comment by BlackSnowDot** [comment]
Check [this](https://github.com/Its-Vichy/PyTerm#-installation) section.

**Comment by AhanafMahmud** [comment]
Thanks I will try

**Comment by AhanafMahmud** [comment]
DEPRECATION: PyTerms is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not insta
lled. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/p
ip/issues/8559

**Comment by AhanafMahmud** [comment]
this is the result i got when i executed ur code

**Comment by AhanafMahmud** [comment]
when i press run it still says no module name pyterm found

**Comment by AhanafMahmud** [comment]
so i finally could install pyterm and this is the screen that i get
    __  __       _   _ _  _____            
         |  \/  |     | | | (_)/ ____|           
         | \  / |_   _| |_| |_| |  __  ___ _ __  
         | |\/| | | | | __| | | | |_ |/ _ \ '_ \ 
         | |  | | |_| | |_| | | |__| |  __/ | | |
         |_|  |_|\__,_|\__|_|_|\_____|\___|_| |_|                                         
                        #MahsaAmini


0 - bluealts
69 - exit

Select service to scrape url >>

**Comment by AhanafMahmud** [comment]
is it suppose to be like this

**Comment by AhanafMahmud** [comment]
But how am i going to generate accounts

**Comment by xX-MoonWalker-Xx** [comment]
enter the number of the service
we only have bluealts right now so it will be 0

**Comment by AhanafMahmud** [comment]
Thanks great work btw
